name: git-husky-setup-workflow
on: 
  push:
    paths:
      - "git-husky-setup/**"
      - ".github/workflows/git-husky-setup-workflow.yml"
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Set up node 
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test